---
permissions:
  contents: write
  pull-requests: write
name: Kubernetes Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  kube-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run kube-score for Kubernetes manifests
      uses: docker://zegl/kube-score:v1.17.0
      with:
        args: "score argocd-autopilot/**/*.yaml"
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: config
        scan-ref: argocd
    - name: Run OWASP ZAP full scan
      uses: docker://owasp/zap2docker-stable:2.14.0
      with:
        args: "zap-full-scan.py -t http://localhost:8080 -J report_json.json -w report_md.md -r report_html.html"
