apiVersion: v1
kind: Service
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  type: NodePort
  ports:
  - port: 80
    name: web
    targetPort: 80
    nodePort: 30080
  - port: 8080
    name: admin
    targetPort: 8080
    nodePort: 30081
  selector:
    app: traefik
