apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        env:
        - name: TZ
          value: "Europe/Berlin"
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole-webpassword
              key: password
        ports:
        - containerPort: 80
        - containerPort: 53
        - containerPort: 53
          protocol: UDP
        volumeMounts:
        - name: etc-pihole
          mountPath: /etc/pihole
        - name: etc-dnsmasq
          mountPath: /etc/dnsmasq.d
      volumes:
      - name: etc-pihole
        emptyDir: {}
      - name: etc-dnsmasq
        emptyDir: {}
