apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heimdall-dashboard
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-headers@kubernetescrd
spec:
  rules:
    - host: heimdall.fle.api64.de
      http:
        paths:
          - path: /dashboard
            pathType: Prefix
            backend:
              service:
                name: heimdall
                port:
                  number: 80
