apiVersion: v1
kind: Service
metadata:
  name: heimdall
spec:
  selector:
    app: heimdall
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
      nodePort: 32680
  type: NodePort
