name: DevSecOps Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-management:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          deny-licenses: GPL-3.0, AGPL-3.0
          fail-on-scopes: runtime, development
          comment-summary-in-pr: true

  iac-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Terrascan
        uses: tenable/terrascan-action@v1.0.0
        with:
          iac_type: terraform
          iac_version: v14
          policy_type: aws
          sarif_upload: true

  application-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Trivy
        uses: aquasecurity/trivy-action@v0.10.0
        with:
          scan-type: fs
          scan-ref: .

      - name: Run ZAP Scan
        uses: zaproxy/action-full-scan@v0.1.0
        with:
          target: "http://localhost:8080"

  ci-cd-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Zizmor
        uses: zizmorcore/zizmor-action@v1.0.0
