name: Dependency Review

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          deny-licenses: GPL-3.0, AGPL-3.0
          fail-on-scopes: runtime, development
          comment-summary-in-pr: true
          repo-token: 0f8f98cfcd7e8cff5c73fca4d4d4681f058ee6c7
