name: MkDocs CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cyberdine-skynet/mkdocs-site
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build MkDocs Docker image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG -f Dockerfile .

      - name: Push image to GHCR
        run: |
          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Install Snyk CLI
        run: |
          curl -sL https://snyk.io/install | bash
          echo "$HOME/.snyk" >> $GITHUB_PATH

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Container Monitor
        run: snyk container monitor $REGISTRY/$IMAGE_NAME:$IMAGE_TAG --file=Dockerfile || true

      - name: Snyk Code Scan (SARIF)
        run: snyk code test --sarif > snyk-code.sarif || true

      - name: Upload Snyk SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-scan

    steps:
      - name: Checkout Argo CD manifests
        uses: actions/checkout@v4
        with:
          repository: cyberdine-skynet/manifests
          token: ${{ secrets.GITHUB_TOKEN }}
          path: manifests

      - name: Update image tag in Argo CD manifest
        run: |
          cd manifests/mkdocs
          sed -i "s|image: ghcr.io/.*/mkdocs-site:.*|image: ghcr.io/cyberdine-skynet/mkdocs-site:${{ github.sha }}|" deployment.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "chore: Update mkdocs-site image to ${{ github.sha }}"
          git push
