name: SAST and DAST Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4

  static-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    needs: dependency-review
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run ESLint
        run: npm run lint
      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1.0.0
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=my_project
            -Dsonar.organization=my_org
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=0f8f98cfcd7e8cff5c73fca4d4d4681f058ee6c7

  dynamic-analysis:
    name: Dynamic Application Security Testing
    runs-on: ubuntu-latest
    needs: static-analysis
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Start Application
        run: |
          docker-compose up -d
          sleep 30  # Wait for the application to be ready
      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.1.0
        with:
          target: "http://localhost:8080"
