name: Example workflow using Snyk fix

on: pull_request

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.ci-skip-step.outputs.ci-skip }}
      skip-not: ${{ steps.ci-skip-step.outputs.ci-skip-not }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Determine CI Skip Conditions
        id: ci-skip-step
        run: |
          if git log -1 --pretty=%B | grep -q 'Merge pull request'; then
            echo "ci-skip=true" >> $GITHUB_OUTPUT
            echo "ci-skip-not=false" >> $GITHUB_OUTPUT
          else
            echo "ci-skip=false" >> $GITHUB_OUTPUT
            echo "ci-skip-not=true" >> $GITHUB_OUTPUT

  security:
    runs-on: ubuntu-latest
    needs: init
    if: ${{ needs.init.outputs.skip == 'false' }}
    steps:
      - uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: fix

      - name: Create a PR
        uses: peter-evans/create-pull-request@v3
        id: cpr
        with:
          base: test

      - name: Get PR info
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
