name: Trivy Image Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  trivy-image-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t my-image:latest .

      - name: Trivy GitHub Action
        uses: anantacloud/trivy-action@v0.0.6
        with:
          image_name: my-image:latest
          scan_type: image
          format: table
          severity: CRITICAL,HIGH,MEDIUM
          exit_code: